feed/urls.py
from django.urls import path

from .views import HomePageView, PostDetailView, AddPostView

app_name = "feed"

urlpatterns = [
    path('', HomePageView.as_view(), name= 'index' ),
    path('detail/<int:pk>/', PostDetailView.as_view(), name= 'detail'),
    path('post/', AddPostView.as_view(), name='post'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from feed import urls as feed_urls
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(feed_urls, namespace='feed'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

feed/models.py
from django.db import models
from sorl.thumbnail import ImageField

class Post(models.Model):
    text = models.CharField(max_length=140, blank=False, null=False)
    image = ImageField()

    def __str__(self):
        return self.text

feed/forms.py
from cProfile import label
from django import forms


class PostForm(forms.Form):
    text = forms.CharField(label='Title')
    image = forms.FileField()

feed/views.py
from django.contrib import messages
from django.views.generic import TemplateView, DetailView, FormView
from .models import Post
from .forms import PostForm

class HomePageView(TemplateView):
    template_name = "home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['posts'] = Post.objects.all().order_by('-id')
        return context
    

class PostDetailView(DetailView):
    template_name = 'detail.html'
    model = Post


class AddPostView(FormView):
    template_name = 'new_post.html'
    form_class = PostForm
    success_url = '/'

    def dispatch(self, request, *args, **kwargs):
        self.request = request
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        #create a new post
        new_object = Post.objects.create(
            text = form.cleaned_data['text'],
            image = form.cleaned_data['image']
        )
        messages.add_message(self.request, messages.SUCCESS, 'Your post was successful')
        return super().form_valid(form)

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}
        default title
        {% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>

<body>
    {% include 'includes/navbar.html' %}
    
    {% if messages %}
        {% for message in messages %}
        <div class="bg-{% if message.tags %}{{ message.tags }} {% else %} success {% endif %} bg-gradient text-center text-white py-3">
            {{ message }}
        </div>
        {% endfor %}
    {% endif %}



    <div class="container">
        {% block body %}
    
        {% endblock body %}
    </div>
</body>

</html>

templates/detail.html
{% extends "base.html" %}

{% block title %}
    Detail View
{% endblock title %}


{% block body %}
    <div class="row">
        <div class="col-sm-10 offset-sm-1 py-5" >
            <h3>{{ object.text }}</h3>
            <img src={{ object.image.url }} class="img-fluid rounded">
        </div>
    </div>
{% endblock body %}

templates/home.html
{% extends "base.html" %}
{% load thumbnail %}

{% block title %}
    My home page
{% endblock title %}


{% block body %}
    <div class="row">

        {% for post in posts %}
        <div class="col-sm-6 col-md-3">     
            <div class="card my-4" >
                {% thumbnail post.image "100x100" crop="center" as im %}
                <img src="{{ im.url }}" class="card-img-top" alt="Image Missing">
                {% endthumbnail %}
                <div class="card-body">
                    <h5 class="card-title">{{ post.text }}</h5>
                    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                    <a href="{% url 'feed:detail' post.id %}" class="btn btn-primary">View full article</a>
                </div>
            </div> 
        </div>
        {% empty %}
            <div class="col-sm-6 py-5 my-5 offset-3 text-center">
                <h3>Welcome!</h3>
                <p>Add your first article</p>
                <a href="{% url 'feed:post' %}" class="btn btn-lg btn-success">Upload</a>
            </div>            
        {% endfor %}
    </div>
    
{% endblock body %}

templates/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">Blog</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'feed:index' %}">Post</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'feed:post' %}">Add Post</a>
          </li>
          
        </ul>
      </div>
    </div>
</nav>

templates/new_post.html
{% extends 'base.html' %}


{% block title %}
    new post
{% endblock title %}
    


{% block body %}
    <form method='POST' action='' enctype='multipart/form-data' class="col-sm-4 offset-4 py-5 my-5">
        <h2 class="mb-4">Upload your article</h2>
        {% csrf_token %}
        {{form.as_p}}
        <div>
            <button type='submit' class="btn btn-lg btn-success">Post</button>
        </div>
    </form>


{% endblock body %}
    